const PDFDocument = require('pdfkit');

/**
 * POST /api/ai/report
 * Generate a professional PDF report
 */
exports.generateReport = async (req, res) => {
    try {
        const { metrics, layout, recommendations, eventDetails } = req.body;

        const doc = new PDFDocument({ margin: 50 });

        // Stream the PDF to the response
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', 'attachment; filename=Event_Analysis_Report.pdf');
        doc.pipe(res);

        // Header
        doc.fontSize(24).text('Event Flow Analysis Report', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Generated for: ${eventDetails?.name || 'Professional Event Plan'}`, { align: 'center' });
        doc.text(`Venue: ${layout.venueSqFt} sq ft | Guests: ${req.body.guestCount} | Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
        doc.moveDown(2);

        // Executive Summary
        doc.fontSize(18).text('Executive Summary', { underline: true });
        doc.fontSize(12).text(`
            This report provides a comprehensive analysis of the event flow and resource requirements for your upcoming event. 
            Based on our simulation of ${req.body.guestCount} guests in a ${layout.venueSqFt} sq ft space, the current layout 
            indicates an average wait time of ${metrics.avgWaitTime} minutes.
        `);
        doc.moveDown();

        // Event Flow Analysis
        doc.fontSize(18).text('Event Flow Analysis', { underline: true });
        doc.fontSize(12).text(`
            - Service Capacity: Our analysis shows a service capacity of ${metrics.serviceCapacity} guests per cycle.
            - Peak Load: We anticipate a peak of ${metrics.peakDiners} diners at the buffet simultaneously.
            - Congestion: ${metrics.congestionZones} potential congestion zones were identified.
        `);
        doc.moveDown();

        // Staffing & Resource Justification
        doc.fontSize(18).text('Staffing & Resource Justification', { underline: true });
        doc.fontSize(12).text(`
            - Recommended Staff: ${recommendations.staff.count} servers.
            Reasoning: ${recommendations.staff.reason}
            - Buffet Configuration: ${recommendations.buffet.recommendedLength} ft recommended.
            Reasoning: ${recommendations.buffet.reason}
            - Resource Requisition: ${recommendations.plates.total} plates required.
            Reasoning: ${recommendations.plates.reason}
        `);
        doc.moveDown();

        // Risk & Improvement Suggestions
        doc.fontSize(18).text('Risk & Improvement Suggestions', { underline: true });
        doc.fontSize(12).text(`
            - Monitor the ${metrics.congestionZones > 0 ? 'identified congestion zones' : 'buffet entry points'} to ensure smooth guest movement.
            - Ensure entry and exit points are clearly marked and unobstructed.
            - Brief the ${recommendations.staff.count} staff members on the peak dining expectations (${metrics.peakDiners} guests).
        `);

        // Footer
        const pageCount = doc.bufferedPageRange().count;
        for (let i = 0; i < pageCount; i++) {
            doc.switchToPage(i);
            doc.fontSize(10).text(
                `Generated by Catery Professional Planner - Confidential`,
                50,
                doc.page.height - 50,
                { align: 'center' }
            );
        }

        doc.end();

    } catch (error) {
        console.error('PDF Generation Error:', error);
        res.status(500).json({ error: 'Failed to generate analysis document.' });
    }
};
